#### Imports

In [2]:
import numpy as np

In [3]:
import time

#### Code

- np built-in functions:

In [4]:
a = np.zeros(4)
a.shape

(4,)

In [5]:
b = np.zeros((4,))
b.shape

(4,)

In [6]:
c = np.random.random_sample(4)
c

array([0.59552277, 0.81382786, 0.34665731, 0.32615558])

In [7]:
c.shape

(4,)

In [8]:
d = np.random.random_sample((4,))
d

array([0.7262245 , 0.88182194, 0.7167455 , 0.88854743])

In [9]:
d.shape

(4,)

- arange fill the array with (start, stop, step)

In [10]:
values = np.arange(5)
values

array([0, 1, 2, 3, 4])

In [11]:
values1 = np.arange(2, 10, 2)
values1

array([2, 4, 6, 8])

In [12]:
values3 = np.arange(10, 2, -2)
values3

array([10,  8,  6,  4])

#### Slice

In [13]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a[-1]

np.int64(9)

In [16]:
a[1:6:1]

array([1, 2, 3, 4, 5])

In [20]:
a[1:10:2]

array([1, 3, 5, 7, 9])

In [22]:
a[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a[:-7]

array([0, 1, 2])

#### Operations on Vectors

In [26]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
b = np.sum(a)
print(b)
c = np.mean(a)
print(c)
d = a**2
print(d)

[1 2 3 4 5 6 7 8]
36
4.5
[ 1  4  9 16 25 36 49 64]


#### Vector Vector wise operations

In [27]:
a = np.array([1,2,3,4,5])
b = np.array([-1,-2,3,4,5])
print(f"Binary operators work element wise: {a+b}")

Binary operators work element wise: [ 0  0  6  8 10]


In [28]:
c = np.array([1,2])
try:
    d = a+c
except Exception as e:
    print(f"The error message: {e}")

The error message: operands could not be broadcast together with shapes (5,) (2,) 


Scaler Scaled Operations

In [29]:
s = np.array([1,2,3,4])
multiply = s * 5
print(multiply)

[ 5 10 15 20]


#### Vector Dot operation

- without using **np.dot()**

In [51]:
def my_dot(a,b):
    x = 0
    for i in range(len(a)):
        x = x + a[i] * b[i]
        print(f"iteration {i}: {x}")
    return x

In [49]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])

In [43]:
a.shape

(4,)

In [52]:
print(f"Dot Product: {my_dot(a,b)}")

iteration 0: -1
iteration 1: -5
iteration 2: 4
iteration 3: 20
Dot Product: 20


- with using **dot product**

In [55]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

dot_product = np.dot(a,b)

dot_product

np.int64(130)

#### Operation on Matrices
- here in .reshape(-1,2)
- the -1 will be replaced automatically with correct dimension
- so it will 6/2 = 3 so it will be (3 rows, 2 columns)

In [56]:
a = np.arange(6).reshape(-1,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])